-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 11:34:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projeto_integrador` DEFAULT CHARACTER SET utf8 ;
USE `db_projeto_integrador` ;

-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone/cel` VARCHAR(25) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo_usuario` ENUM('CLIENTE', 'PRESTADOR') NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_categoria` (
  `id_categoria` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_categoria` ENUM('TERAPIA', 'FARMACIA', 'ASSISTENCIA SOCIAL', 'CLINICA') NOT NULL,
  `modo_atend` ENUM('PRESENCIAL', 'ONLINE') NOT NULL,
  `motivo` ENUM('ALCOOLISMO', 'VICIO EM DROGAS', 'DOENÇA EMOCIONAL/MENTAL', 'NUTRICIONISTA', 'ACOLHIMENTO') NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_servico` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(2000) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `foto_profissional` VARCHAR(255) NOT NULL,
  `avaliacao_atendimento` VARCHAR(255) NOT NULL,
  `fk_categoria` BIGINT NOT NULL,
  `fk_usuario` BIGINT NOT NULL,
  `tb_categoria_id_categoria` BIGINT NOT NULL,
  `tb_usuario_id_usuario` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `tb_usuario_id_usuario`),
  INDEX `fk_tb_servico_tb_categoria_idx` (`tb_categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_tb_servico_tb_usuario1_idx` (`tb_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_servico_tb_categoria`
    FOREIGN KEY (`tb_categoria_id_categoria`)
    REFERENCES `db_projeto_integrador`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_servico_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id_usuario`)
    REFERENCES `db_projeto_integrador`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
